#!/usr/bin/env python3
"""Scan the seven-mod-32 residual branch for long finite stabilized survivor runs.

Purpose: falsify finite-window versions of the desired asymptotic obstruction.
A positive integer n whose valuation prefix is coefficient-safe has canonical
residue exactly n once 2^S > n.  From that point until its first descent, every
higher 2-adic lift digit is zero.  Long stopping-time records therefore produce
long stretches that look exactly like the forbidden "eventual stabilization"
condition, except that they eventually terminate.

The scan enumerates all lifts of the 395 base residual classes below 2^K.
"""
from __future__ import annotations
import argparse, json, math
from pathlib import Path

L=math.log2(3.0)
S13={679,1191,2663,3687,4199,4455,5191,5607,5959,6215,6375,6631,6983,7079,7399,7495,7847,7911,8103}
S15={839,1095,2119,2279,2727,2983,3303,4007,6503,6759,7783,9959,10055,11079,11943,12967,14439,16743,16871,17735,17767,19623,20199,21223,23399,24647,24679,25703,25831,26087,26535,27111,27975,28999,29863,30311,30887}
S16={359,1351,2407,2791,2887,3239,3815,4775,5863,6247,7015,8263,8551,9319,9543,10151,10727,11431,12007,12615,12775,13671,13927,14503,15207,16455,17127,17223,17479,17511,18343,18919,19111,19367,19687,20807,21735,22119,22695,22887,23143,25415,25671,26343,26439,27303,27559,27879,28327,31079,31335,33255,34151,34535,34631,36519,37607,37735,40039,41063,41447,42215,42343,42471,43111,43335,44359,45223,45799,46247,46407,48295,49255,50407,50663,51271,51431,52071,52551,53159,53319,54375,54439,55207,56935,57671,58983,59463,59559,59623,60231,61351,62119,62279,63335,63591,64167,64871,65127}

def old_residual(n:int)->bool:
    return (n%128 in {39,71,103}
      and n%256 not in {39,199}
      and n%1024 not in {423,583,999}
      and n%4096 not in {231,615,935,1703,3143,3559,3911}
      and n%8192 not in S13 and n%32768 not in S15 and n%65536 not in S16)

BASES=[n for n in range(1<<16) if old_residual(n)]
assert len(BASES)==395

def v2(n:int)->int:
    return (n & -n).bit_length()-1

def analyze(n:int, limit:int=10000):
    x=n; S=0; rows=[]
    first_stable=None
    for t in range(1,limit+1):
        z=3*x+1; a=v2(z); x=z>>a; S+=a
        D=math.floor(t*L)-S
        if first_stable is None and (1<<S)>n:
            first_stable=t
        rows.append((t,x,a,S,D))
        if x<n:
            safe_rows=rows[:-1] if D<0 else rows
            late={}
            for cutoff in (20,50,100,150,200):
                vals=[(D0/t0,t0,D0) for t0,_,_,_,D0 in safe_rows if t0>=cutoff and D0>=0]
                if vals: late[str(cutoff)]=min(vals)
            zero_hits=[t0 for t0,_,_,_,D0 in safe_rows if D0==0]
            return {
              "stopping_time":t,
              "total_exponent":S,
              "descent_value":x,
              "first_canonical_stabilization_step":first_stable,
              "zero_lift_run_before_descent": (t-first_stable) if first_stable is not None else 0,
              "max_safe_slack":max((r[4] for r in safe_rows),default=0),
              "last_zero_slack_step":max(zero_hits) if zero_hits else None,
              "late_min_slack_ratio":late,
            }
    return None

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--depth",type=int,default=30)
    ap.add_argument("--output",default="agent-state/collatz-stabilization-records.json")
    args=ap.parse_args()
    if not (16<=args.depth<=32): raise SystemExit("depth must be 16..32")
    lifts=1<<(args.depth-16)
    records=[]
    best_t=-1
    best_zero=-1
    zero_record=None
    checked=0
    for base in BASES:
        for k in range(lifts):
            n=base+(k<<16)
            st=analyze(n)
            checked+=1
            if st is None: continue
            if st["stopping_time"]>best_t:
                best_t=st["stopping_time"]
                records.append({"n":n,**st})
            if st["zero_lift_run_before_descent"]>best_zero:
                best_zero=st["zero_lift_run_before_descent"]
                zero_record={"n":n,**st}

    # compact all-time stopping records by increasing n scan order is not guaranteed,
    # so retain only strict stopping-time record events generated by enumeration plus
    # the true best record.
    best=max(records,key=lambda x:x["stopping_time"])
    report={
      "depth":args.depth,
      "candidate_count":checked,
      "base_residue_count":len(BASES),
      "best_stopping_record":best,
      "best_zero_lift_record":zero_record,
      "record_events":records,
      "interpretation":{
        "finite_window_no_go":(
          "Once 2^S>n, the canonical residue is literally n.  Thus "
          "zero_lift_run_before_descent counts consecutive exact stabilization "
          "steps before the orbit finally defeats coefficient safety.  Long "
          "runs with late zero-slack hits show that no fixed finite window of "
          "stabilization plus criticality can rule out positive integers."
        )
      }
    }
    out=Path(args.output); out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(json.dumps(report,indent=2,sort_keys=True)+"\n")
    print(json.dumps({
      "checked":checked,
      "best_n":best["n"],
      "best_stopping_time":best["stopping_time"],
      "best_zero_lift_n":zero_record["n"],
      "best_zero_lift_run":zero_record["zero_lift_run_before_descent"],
      "best_late_zero_slack_step":best["last_zero_slack_step"],
    },indent=2))

if __name__=="__main__": main()
